CFLAGS = -std=c99 -Wall -Werror -Wextra -Wsign-conversion -Wconversion -Wshadow -Wdouble-promotion -pedantic -lm -g
CXXFLAGS = -Wall -Werror -Wextra -Wsign-conversion -Wconversion -Wshadow -Wdouble-promotion -pedantic -lm

LIBS = -lm
